export const homeHref = '#';
export const graphicDesignHref = '#graphic_design';
export const portfolioHref = graphicDesignHref;
export const uxUiDesignHref = '#ux_ui_design';
export const cvHref =
  'https://drive.google.com/file/d/1XbIgZhtxzaa_Ykrbk0Jv5ENrRdPkMMDr/view?usp=sharing';
export const linkedinHref = 'https://www.linkedin.com/in/henyaadler/';
export const facebookHref = 'https://www.facebook.com/henyadesign';
export const whatsAppHref = 'https://wa.me/972587782776';
export const mailHref = 'mailto:henyadesign@gmail.com';
